onmagnoliasquare/website

.gitignore, .vscode/settings.json, backend/package.json, backend/sanity.config.ts, backend/schemaTypes/article.ts, backend/schemaTypes/category.ts, backend/schemaTypes/index.ts, backend/schemaTypes/member.ts, backend/schemaTypes/objects/blockContent.ts, backend/schemaTypes/objects/socialHandles.ts, backend/schemaTypes/tag.ts, yarn.lock
=> feat(back): implement basic schematypes

.github/workflows/enforcer-main.yml, .github/workflows/enforcer-staging.yml
=> PR Enforcement Actions

backend/README.md, backend/lib/slugValidator.ts, backend/package.json, backend/schemaTypes/article.ts, backend/schemaTypes/category.ts, backend/schemaTypes/index.ts, backend/schemaTypes/series.ts, yarn.lock
=> Add slug validation and series

.github/workflows/backend.yml, .github/workflows/frontend.yml, README.md, package.json
=> 43 refactor development and deployment pipeline

packages/frontend/src/lib/sanity.ts
`sort` category posts by date.
=> refactor(f): add `sort` to category groq query

README.md, packages/frontend/src/lib/sanity.ts, packages/frontend/src/routes/(app)/category/[category=categories]/[slug]/+page.svelte
**Documentation**
- Added Windows section in `readme` for  `yarn` installation troubleshooting.
**Frontend**
- Restructured `sanity.ts` query to include `category` _name_ and _slug_.
- Added `feature` to display `category` on byline.
=> 100 category after author name

packages/backend/schemaTypes/article.ts, packages/backend/schemaTypes/member.ts, packages/backend/schemaTypes/objects/blockContent.ts, packages/backend/schemaTypes/objects/fromLocation.ts
Improved wording and explicitness of the description text for backend fields. Also added periods `.` to end sentences.
=> Improve backend description text

packages/frontend/src/components/about/StaffClickable.svelte, packages/frontend/src/components/about/StaffGrid.svelte, packages/frontend/src/components/authorPage/Location.svelte, packages/frontend/src/lib/sanity.ts, packages/frontend/src/routes/(app)/about/staff/+page.svelte, packages/frontend/src/routes/(app)/about/staff/[name]/+page.svelte, packages/frontend/src/styles/onmagnoliasquare.css
The staff page now includes headshots, and a grid view.
- New components for `StaffClickable` and `StaffGrid`.
=> Small staff page rework

packages/backend/lib/abbreviateName.ts, packages/backend/lib/checkWhitespace.ts, packages/backend/lib/index.test.ts, packages/backend/lib/slugValidator.ts, packages/backend/lib/validUrl.ts, packages/backend/lib/validationHelpers.ts, packages/backend/schemaTypes/article.ts, packages/backend/schemaTypes/category.ts, packages/backend/schemaTypes/index.ts, packages/backend/schemaTypes/member.ts, packages/backend/schemaTypes/objects/accessibleImage.ts, packages/backend/schemaTypes/objects/dateInfo.ts, packages/backend/schemaTypes/objects/embeddedLink.ts, packages/backend/schemaTypes/objects/fromLocation.ts, packages/backend/schemaTypes/objects/socialHandles.ts, packages/backend/schemaTypes/primitives/formattedString.ts, packages/backend/schemaTypes/primitives/formattedText.ts, packages/backend/schemaTypes/primitives/requiredFormattedString.ts, packages/backend/schemaTypes/primitives/requiredFormattedText.ts, packages/backend/schemaTypes/series.ts, packages/backend/schemaTypes/tag.ts
Several backend changes. Frontend has been receiving too much love.
- New functions: `checkWhitespace` and `abbreviateName`.
- Whitespace checking for all `string` and `text` fields. This was done by creating new primitive types for the schema to use. See c39e2d78599e735c7dbcab4102fa811d58e98eee.
- Fix article previews so that they show an article's header image rather than nothing.
=> Backend validation additions and 

packages/frontend/src/lib/sanity.ts, packages/frontend/src/lib/schema.d.ts, packages/frontend/src/routes/(app)/about/staff/[name]/+page.server.ts, packages/frontend/src/routes/(app)/about/staff/[name]/+page.svelte, packages/frontend/tests/test.ts
Added a query to render committee someone is a part of on frontend.
=> Render committee name on author page

.github/workflows/deploy-staging.yml, .github/workflows/staging.yml
=> ci: add artifact upload/download

packages/frontend/src/routes/(app)/category/[category=categories]/+page.server.ts
=> fix: remove dead `if` statements

.github/workflows/main.yml, packages/frontend/src/routes/+layout.svelte
=> ci: update run logic

.github/workflows/main.yml, packages/frontend/src/routes/+layout.svelte
=> ci: add event_names

.github/workflows/main.yml, packages/frontend/src/routes/+error.svelte
=> ci: reorder build actions

.github/workflows/main.yml, packages/frontend/src/routes/(app)/+layout.svelte
=> ci: delete dl artifact

.github/workflows/main.yml, .github/workflows/staging.yml, packages/frontend/src/routes/(home)/+page.server.ts
=> ci: up environment staaging order

packages/frontend/src/lib/navRoutes.ts
=> refactor(f): remove unused nav route

.github/workflows/main.yml, packages/frontend/src/lib/navRoutes.ts, packages/frontend/src/lib/sanity.ts
=> Fix CI deployments

.github/workflows/deploy-release.yml
Corrected `outputs` to be `build` rather than `setup`.
=> ci: change `YARN_VERSION` needs

.github/workflows/deploy-release.yml, packages/backend/package.json, wrangler.toml
Added CI changes to frontend with Wrangler config and main branch deployment.
=> Update frontend wrangler deployment

packages/frontend/src/components/general/MobileNavbar.svelte
On mobile, navbar would display dots for the list. This is a fix.
=> fix(f): remove mobile nav list dot

.github/workflows/deploy-release.yml, .github/workflows/deploy-staging.yml, .github/workflows/main.yml, packages/backend/wrangler.toml, packages/frontend/wrangler.toml
Add `wrangler.toml` to respective frontend/backend packages. Updated CI commands to reflect these config changes.
=> Fix `wrangler.toml`

.github/workflows/deploy-release.yml, .github/workflows/deploy-staging.yml, .github/workflows/main.yml, packages/backend/wrangler.toml, packages/frontend/wrangler.toml
=> Fix wrangler toml

packages/backend/wrangler.toml, packages/frontend/wrangler.toml
Added name field back to `wrangler.toml`.
=> fix: add `name` field back to `wrangler.toml`

packages/frontend/src/components/home/ArticleBoxC.svelte, packages/frontend/src/lib/sanity.ts, packages/frontend/src/routes/(app)/category/[category=categories]/+page.server.ts, packages/frontend/src/routes/(app)/category/[category=categories]/+page.svelte, packages/frontend/src/routes/api/category/[category=categories]/+server.ts
- Added `blurHash` to `ArticleBoxC` and API query.
- Removed some unncessary comments and fixtures.
- Use staging dataset when building in frontend.
=> Minor CSS and querying updates

packages/frontend/src/components/Footer.svelte, packages/frontend/src/components/Image.svelte, packages/frontend/src/components/defaults/P.svelte, packages/frontend/src/components/home/DateLine.svelte, packages/frontend/src/components/home/DesktopLanding.svelte, packages/frontend/src/components/home/DesktopLandingNavbar.svelte, packages/frontend/src/components/portabletext/ArticleSingleComponentBlock.svelte, packages/frontend/src/lib/navRoutes.ts, packages/frontend/src/routes/(home)/+layout.svelte, packages/frontend/src/routes/(home)/+page.svelte, packages/frontend/src/routes/+layout.svelte, packages/frontend/src/theme.css, packages/frontend/tests/integration/tagPage.test.ts, packages/frontend/tests/integration/test.ts
Revamped homepage styling.
- Implemented typography guide sizing, closes #33 
- Cleaned up homepage look and feel. Much cleaner.
- Adjusted footer headings.
- Added aspect ratio to `<Image>` props.
-
=> Homepage styling refactor

packages/frontend/src/components/CardLink.svelte, packages/frontend/src/components/about/CodeOfEthics.svelte, packages/frontend/src/routes/(app)/about/+page.svelte
Changed sizes of about page font, and adjusted some wording.
=> Refactor about page sizes

.github/workflows/deploy-staging.yml, .github/workflows/push-to-staging.yml
=> ci: separate staging merge and deploy

.github/workflows/main.yml, .github/workflows/push-to-main.yml, .github/workflows/push-to-staging.yml, packages/frontend/playwright.config.ts, packages/frontend/tests/functional/v05ArticleAccessibility.test.ts, packages/frontend/tests/functional/v05ArticleFeatures.test.ts, packages/frontend/tests/integration/apiAccessibility.test.ts, packages/frontend/tests/integration/articlePage.test.ts, packages/frontend/tests/integration/memberPage.test.ts, packages/frontend/tests/integration/redirects.test.ts, packages/frontend/tests/integration/test.ts, packages/frontend/tests/testVariables.ts
- Grouped and organized tests with Playwright.
- Added permission fields to push workflows. This maintains security.
=> Organize playwright tests and workflow perms

package.json, packages/backend/package.json, packages/frontend/package.json, packages/frontend/postcss.config.mjs, packages/frontend/src/tests/unit/client.test.ts, packages/frontend/vite.config.ts, yarn.lock
=> chore: up deps, remove postcss

packages/frontend/src/components/general/MobileNavbar.svelte, packages/frontend/src/components/general/Navbar.svelte
=> Add aria-label to nav

package.json, packages/backend/package.json, packages/frontend/package.json, yarn.lock
=> chore: up deps

package.json
=> chore: bump yarn version

package.json, packages/backend/package.json, packages/frontend/package.json, yarn.lock
=> feat: up deps
